///<reference path="../typings/tsd.d.ts"/>
///<reference path="services/models.ts"/>
///<reference path="services/pull_request_repository.ts"/>
///<reference path="services/notification_repository.ts"/>
///<reference path="services/socket.ts"/>
///<reference path="services/socket_handler.ts"/>
///<reference path="services/notifier.ts"/>
///<reference path="services/config.ts"/>
///<reference path="services/indicator.ts"/>
///<reference path="components/background_component/background_component.ts"/>
///<reference path="components/pull_request_component/pull_request_component.ts" />
///<reference path="components/pull_requests_list_component/pull_requests_list_component.ts"/>
///<reference path="components/pull_requests_header_component/pull_requests_header_component.ts"/>
///<reference path="components/approval_progress_component/approval_progress_component.ts"/>
///<reference path="components/user_vote_component/user_vote_component.ts"/>
///<reference path="components/options_component/options_component.ts"/>
///<reference path="components/section_title_component/section_title_component.ts"/>
///<reference path="components/pull_request_link_component/pull_request_link_component.ts"/>
///<reference path="components/navigation_bar_component/navigation_bar_component.ts"/>
///<reference path="filters/authored_filter.ts"/>
///<reference path="filters/assigned_filter.ts"/>

